import { Picture } from './picture';

export const PICTURES: Picture[] = [
    {id:1,name:'Complexe',url: '../../assets/images/macro/macro2.JPG',categorie:['macro']},
    {id:6,name:'Focus',url: '../../assets/images/bn/bw1.JPG',categorie:['bn']},
    {id:39,name:'Les hommes de dieu',url: '../../assets/images/film/film2.JPG',categorie:['film']},
    {id:8,name:'Peur',url: '../../assets/images/bn/bw3.JPG',categorie:['bn']},
    {id:2,name:'Precision',url: '../../assets/images/macro/macro3.JPG',categorie:['macro']},
    {id:40,name:'Les hommes de dieu',url: '../../assets/images/film/film3.JPG',categorie:['film']},
    {id:28,name:'Jazz Concert',url: '../../assets/images/jazz/concert2.JPG',categorie:['concert']},
    {id:9,name:'Bravour',url: '../../assets/images/bn/bw4.JPG',categorie:['bn']},
    {id:32,name:'Jazz Concert',url: '../../assets/images/jazz/concert6.JPG',categorie:['concert','bn']},
    {id:5,name:'The welcoming sun',url: '../../assets/images/macro/macro.jpg',categorie:['macro','bn']},
    {id:10,name:'Malheur',url: '../../assets/images/bn/bw5.jpg',categorie:['bn']},
    {id:41,name:'Les hommes de dieu',url: '../../assets/images/film/film4.JPG',categorie:['film']},
    {id:29,name:'Jazz Concert',url: '../../assets/images/jazz/concert3.JPG',categorie:['concert','bn']},
    {id:11,name:'Joie',url: '../../assets/images/mariage/mariage.jpg',categorie:['mariage','bn']},
    {id:12,name:'Sourire',url: '../../assets/images/mariage/mariage13.JPG',categorie:['mariage','bn']},
    {id:7,name:'Action',url: '../../assets/images/bn/bw2.JPG',categorie:['bn']},
    {id:42,name:'Les hommes de dieu',url: '../../assets/images/film/film5.JPG',categorie:['film']},
    {id:17,name:'Tendresse',url: '../../assets/images/mariage/mariage11.JPG',categorie:['mariage','bn']},
    {id:24,name:'Joueurs',url: '../../assets/images/portrait/portrait13.JPG',categorie:['portrait']},
    {id:13,name:'Protection',url: '../../assets/images/mariage/mariage9.JPG',categorie:['mariage','bn']},
    {id:14,name:'Pour la vie',url: '../../assets/images/mariage/mariage7.JPG',categorie:['mariage']},
    {id:4,name:'The welcoming sun',url: '../../assets/images/macro/macro5.jpg',categorie:['macro']},
    {id:43,name:'Les hommes de dieu',url: '../../assets/images/film/film6.JPG',categorie:['film']},
    {id:15,name:'Future',url: '../../assets/images/mariage/mariage4.JPG',categorie:['mariage','bn']},
    {id:33,name:'Jazz Concert',url: '../../assets/images/jazz/concert7.JPG',categorie:['concert','bn']},
    {id:16,name:'Galenterie',url: '../../assets/images/mariage/mariage10.JPG',categorie:['mariage','bn']},
    {id:25,name:'Percant',url: '../../assets/images/portrait/portrait9.JPG',categorie:['portrait']},
    {id:18,name:'Amour',url: '../../assets/images/mariage/mariage12.JPG',categorie:['mariage','bn']},
    {id:44,name:'Les hommes de dieu',url: '../../assets/images/film/film7.JPG',categorie:['film']},
    {id:35,name:'Jazz Concert',url: '../../assets/images/jazz/concert9.JPG',categorie:['concert','bn']},
    {id:19,name:'Serinite',url: '../../assets/images/portrait/baby2.JPG',categorie:['portrait','bn']},
    {id:20,name:'Curiosite',url: '../../assets/images/portrait/portrait3.JPG',categorie:['portrait','bn']},
    {id:21,name:'Concentration',url: '../../assets/images/portrait/portrait1.JPG',categorie:['portrait']},
    {id:45,name:'Les hommes de dieu',url: '../../assets/images/film/film8.JPG',categorie:['film']},
    {id:31,name:'Jazz Concert',url: '../../assets/images/jazz/concert5.JPG',categorie:['concert']},
    {id:22,name:'Sy Fi',url: '../../assets/images/portrait/portrait7.JPG',categorie:['portrait']},
    {id:23,name:'En famille',url: '../../assets/images/portrait/portrait12.JPG',categorie:['portrait']},
    {id:30,name:'Jazz Concert',url: '../../assets/images/jazz/concert4.JPG',categorie:['concert','bn']},
    {id:46,name:'Les hommes de dieu',url: '../../assets/images/film/film9.JPG',categorie:['film']},
    {id:26,name:'Douceur',url: '../../assets/images/portrait/baby1.JPG',categorie:['portrait']},
    {id:27,name:'Jazz Concert',url: '../../assets/images/jazz/concert1.JPG',categorie:['concert']},
    {id:34,name:'Jazz Concert',url: '../../assets/images/jazz/concert8.JPG',categorie:['concert','bn']},
    {id:47,name:'Les hommes de dieu',url: '../../assets/images/film/film10.JPG',categorie:['film']},
    {id:36,name:'Douceur',url: '../../assets/images/portrait/baby3.JPG',categorie:['portrait']},
    {id:37,name:'Star',url: '../../assets/images/portrait/portrait11.JPG',categorie:['portrait']},
    {id:38,name:'Les hommes de dieu',url: '../../assets/images/film/film1.JPG',categorie:['film']},
    {id:48,name:'Star',url: '../../assets/images/portrait/portrait2.JPG',categorie:['portrait','bn']},
	{id:49,name:'Sourire',url: '../../assets/images/mariage/mariage3.JPG',categorie:['mariage']},

]
    


